### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by lion1505** [Plutokekz/MVG-Api#2]
I'm receiving a JSONDecodeError when executing the example code.

**Comment by Plutokekz** [comment]
The endpoints has been modified by mvg, making the current one obsolete. I am currently investigating and working on resolving this.

**Comment by Plutokekz** [comment]
Resolved in version 0.1.5: Updated the endpoints as per mvg's changes, ensuring compatibility and resolving the issue @lion1505
